name: PKU Mail Login
on: 
  push:
  schedule:
    - cron: '5,10,15,20,25,30,35,40,45,50,55,0 * * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.2.2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - uses: browser-actions/setup-chrome@latest
    - run: python -m pip install --upgrade pip
    - run: pip install splinter
    - name: Run Login
      env:
        USERS: ${{ secrets.USERS }}
      run: python login.py
